### Don't change any of these — GitHub Pages requires them
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

title: CRPG Walkthroughs
email: cordes.ben@gmail.com
description: >-
  A collection of walkthroughs for computer RPGs, mostly from the 1990s.
# baseurl: /
# url:
github_username: fraterrisus

# exclude:
#   - useless.file.txt
